server:
  servlet:
    context-path: /hr

spring:
  profiles:
    active:
      - smart

    thymeleaf:
          cache: false

    mvc:
        format:
            date: yyyy-MM-dd
            date-time: yyyy-MM-dd HH:mm:ss

hr:
    salary:
      a-default:
          percent: 5
      a-smart:
        limits:
          1: 2
          2.5: 5
          5: 10
          10: 20
          7.5: 15
          15: 30
          25: 40